### ISSUE TITLE
How did you get the 3DCaricShop dataset

### ISSUE THREAD

**Issue by onion-liu** [ycjungSubhuman/DeepDeformable3DCaricatures#1]
Hi,

Impressive results of your paper!

The 3DCaricShop dataset has not been released on their homepage and github (https://github.com/qiuyuda/3DCaricShop). Could you tell me how you got the dataset?

**Comment by ycjungSubhuman** [comment]
Hi,

Thanks for the interest in our paper.

I contacted the authors directly via email.

Best regards,
Yucheol Jung
________________________________
From: onion ***@***.***>
Sent: Monday, August 1, 2022 4:26:43 PM
To: ycjungSubhuman/DeepDeformable3DCaricatures ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ycjungSubhuman/DeepDeformable3DCaricatures] How did you get the 3DCaricShop dataset (Issue #1)


Hi,

Impressive results of your paper!

The 3DCaricShop dataset has not been released on their homepage and github (https://github.com/qiuyuda/3DCaricShop). Could you tell me how you got the dataset?
