### ISSUE TITLE
How to train the model

### ISSUE THREAD

**Issue by WangJYao** [ycjungSubhuman/DeepDeformable3DCaricatures#2]
Hi！
Your paper is well written！
If I get the 3DCaricShop data set, how can I train the model next？

**Comment by ycjungSubhuman** [comment]
Sorry, we are still preparing the training code. In the meantime you may implement the training loop based on this test code. Thanks!

**Comment by WangJYao** [comment]
Is it the code "training_loop_surface. Py" ？

**Comment by ycjungSubhuman** [comment]
You may refer to the code when building your own training loop. In our repository, the train() function is only used for latent code optimization currently.

**Comment by WangJYao** [comment]
Please forgive me for asking you many questions.
I urgently need to  the training code
This is my first time writing the training code，it is below.  I know it is not a complete training code.
I need your help!

```
import` configargparse
import os
import torch
from torch.utils.data import DataLoader, Dataset
from dataset_caricshop3d import CaricShop3DTrain
from surface_net import SurfaceDeformationField
def main():
    print(opt)
    meta_params = vars(opt)
    model = SurfaceDeformationField(1268, **meta_params)
    train_dataset = CaricShop3DTrain(opt.dir, num_samples=11551)
    train_dataloader = DataLoader(dataset=train_dataset, batch_size=opt.batch_size)
    optimizer = torch.optim.Adam(lr=opt.lr, betas=(opt.b1, opt.b2))
    for epoch in range(opt.epochs):
        for idx, ds in enumerate(train_dataloader):
            loss = model.forward(ds.observations,ds.ground_truth)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

    torch.save(model.state_dict(), 'model.pth')
if __name__ == '__main__':
    os.environ['CUDA_VISIBLE_DEVICES'] = '0'
    p = configargparse.ArgumentParser()
    p.add_argument("--dir", type=str, default="dataset", help="3DCaricShop dataset root")
    p.add_argument("--epoch", type=int, default=500)
    p.add_argument("--batch_size", type=int, default=128)
    p.add_argument("--lr", type=float, default=1e-4, help="adam: learning rate")
    p.add_argument("--b1", type=float, default=0.9)
    p.add_argument("--b2", type=float, default=0.999)
    p.add_argument('--model_type', type=str, default='sine')
    p.add_argument('--latent_dim', type=int, default=128, help='latent code dimension.')
    p.add_argument('--hidden_num', type=int, default=128, help='hidden layer dimension of deform-net.')
    p.add_argument('--num_hidden_layers', type=int, default=3, help='number of hidden layers of deform-net.')
    p.add_argument('--hyper_hidden_layers', type=int, default=1, help='number of hidden layers hyper-net.')
    opt = p.parse_args()
    main()
```

**Comment by ycjungSubhuman** [comment]
I have some urgent work to do right now, so please forgive me for not giving the 100% solution for your code.
If you add ", params=model.parameters()" to torch.optim.Adam() constructer I think your code should work. Also, don't forget to move the model to GPU with "model = SurfaceDeformationField(1268, **meta_params).cuda()".

Note that you need to check validation error using a small number of validation set during the training (e.g., save checkpoint frequently and calculate validation errors after training is done). If you train the model too much, the model will suffer from overfitting.

**Comment by WangJYao** [comment]
Thank you for your reply! It's very useful!
I modified my code according to "training_loop_surface. Py" and your reply. It can work successfully.
But I don't know how to write the function calculate validation errors.
And what else can be modified？

···
import configargparse
import os
import torch
import time
import numpy as np
from tqdm.autonotebook import tqdm
from torch.utils.data import DataLoader, Dataset
from dataset_caricshop3d import CaricShop3DTrain
from surface_net import SurfaceDeformationField

# def valid(model, valid_dataloader):

def main():
    checkpoints_dir = os.path.join(opt.model_dir, 'checkpoints')
    meta_params = vars(opt)
    model = SurfaceDeformationField(1268, **meta_params).cuda()
    params = model.parameters()
    train_dataset = CaricShop3DTrain(opt.dir, num_samples=11551)
    train_dataloader = DataLoader(dataset=train_dataset, batch_size=opt.batch_size)

    optimizer = torch.optim.Adam(params, lr=opt.lr)
    total_steps = 0
    steps_til_summary = opt.epochs_til_checkpoint
    with tqdm(total=len(train_dataloader) * opt.epochs) as pbar:
        train_losses = []
        for epoch in range(opt.epochs):
            if not epoch % opt.epochs_til_checkpoint:
                torch.save(model.state_dict(),
                           os.path.join(checkpoints_dir, 'model_epoch_%04d.pth' % epoch))
                np.savetxt(os.path.join(checkpoints_dir, 'train_losses_epoch_%04d.txt' % epoch),
                           np.array(train_losses))
                # valid(model,valid_dataloader)

            for i, (model_input, gt) in enumerate(train_dataloader):
                start_time = time.time()
                model_input = {key: value.cuda() for key, value in model_input[0].items()}
                gt = {key: value.cuda() for key, value in gt[0].items()}

                losses = model.forward(model_input, gt)
                train_loss = 0.
                for loss_name, loss in losses.items():
                    single_loss = loss.mean()
                    train_loss += single_loss
                train_losses.append(train_loss.item())

                optimizer.zero_grad()
                train_loss.backward()
                optimizer.step()
                pbar.update(1)
                if not total_steps % steps_til_summary:
                    tqdm.write("Epoch %d, Total loss %0.6f, iteration time %0.6f" % (epoch, train_loss, time.time() - start_time))
                total_steps += 1

        torch.save(model.state_dict(),
                   os.path.join(checkpoints_dir, 'model_final.pth'))
        np.savetxt(os.path.join(checkpoints_dir, 'train_losses_final.txt'),
                   np.array(train_losses))


if __name__ == '__main__':
    os.environ['CUDA_VISIBLE_DEVICES'] = '0'

    p = configargparse.ArgumentParser()
    p.add_argument("--dir", type=str, default="dataset", help="3DCaricShop dataset root")
    p.add_argument("--model_dir", type=str, default="model", help="")
    p.add_argument("--epochs", type=int, default=50)
    p.add_argument("--epochs_til_checkpoint", type=int, default=10)
    p.add_argument("--batch_size", type=int, default=4)
    p.add_argument("--lr", type=float, default=1e-4, help="adam: learning rate")
    p.add_argument('--model_type', type=str, default='sine')
    p.add_argument('--latent_dim', type=int, default=128, help='latent code dimension.')
    p.add_argument('--hidden_num', type=int, default=128, help='hidden layer dimension of deform-net.')
    p.add_argument('--num_hidden_layers', type=int, default=3, help='number of hidden layers of deform-net.')
    p.add_argument('--hyper_hidden_layers', type=int, default=1, help='number of hidden layers hyper-net.')

    opt = p.parse_args()
    main()
···

**Comment by WangJYao** [comment]
Thank you for your reply! It's very useful!
I modified my code according to "training_loop_surface. Py" and your reply. It can work successfully.
But I don't know how to write the function calculate validation errors.
And what else can be modified？

```
import configargparse
import os
import torch
import time
import numpy as np
from tqdm.autonotebook import tqdm
from torch.utils.data import DataLoader, Dataset
from dataset_caricshop3d import CaricShop3DTrain
from surface_net import SurfaceDeformationField

# def valid(model, valid_dataloader):

def main():
    checkpoints_dir = os.path.join(opt.model_dir, 'checkpoints')
    meta_params = vars(opt)
    model = SurfaceDeformationField(1268, **meta_params).cuda()
    params = model.parameters()
    train_dataset = CaricShop3DTrain(opt.dir, num_samples=11551)
    train_dataloader = DataLoader(dataset=train_dataset, batch_size=opt.batch_size)

    optimizer = torch.optim.Adam(params, lr=opt.lr)
    total_steps = 0
    steps_til_summary = opt.epochs_til_checkpoint
    with tqdm(total=len(train_dataloader) * opt.epochs) as pbar:
        train_losses = []
        for epoch in range(opt.epochs):
            if not epoch % opt.epochs_til_checkpoint:
                torch.save(model.state_dict(),
                           os.path.join(checkpoints_dir, 'model_epoch_%04d.pth' % epoch))
                np.savetxt(os.path.join(checkpoints_dir, 'train_losses_epoch_%04d.txt' % epoch),
                           np.array(train_losses))
                # valid(model,valid_dataloader)

            for i, (model_input, gt) in enumerate(train_dataloader):
                start_time = time.time()
                model_input = {key: value.cuda() for key, value in model_input[0].items()}
                gt = {key: value.cuda() for key, value in gt[0].items()}

                losses = model.forward(model_input, gt)
                train_loss = 0.
                for loss_name, loss in losses.items():
                    single_loss = loss.mean()
                    train_loss += single_loss
                train_losses.append(train_loss.item())

                optimizer.zero_grad()
                train_loss.backward()
                optimizer.step()
                pbar.update(1)
                if not total_steps % steps_til_summary:
                    tqdm.write("Epoch %d, Total loss %0.6f, iteration time %0.6f" % (epoch, train_loss, time.time() - start_time))
                total_steps += 1

        torch.save(model.state_dict(),
                   os.path.join(checkpoints_dir, 'model_final.pth'))
        np.savetxt(os.path.join(checkpoints_dir, 'train_losses_final.txt'),
                   np.array(train_losses))


if __name__ == '__main__':
    os.environ['CUDA_VISIBLE_DEVICES'] = '0'

    p = configargparse.ArgumentParser()
    p.add_argument("--dir", type=str, default="dataset", help="3DCaricShop dataset root")
    p.add_argument("--model_dir", type=str, default="model", help="")
    p.add_argument("--epochs", type=int, default=50)
    p.add_argument("--epochs_til_checkpoint", type=int, default=10)
    p.add_argument("--batch_size", type=int, default=4)
    p.add_argument("--lr", type=float, default=1e-4, help="adam: learning rate")
    p.add_argument('--model_type', type=str, default='sine')
    p.add_argument('--latent_dim', type=int, default=128, help='latent code dimension.')
    p.add_argument('--hidden_num', type=int, default=128, help='hidden layer dimension of deform-net.')
    p.add_argument('--num_hidden_layers', type=int, default=3, help='number of hidden layers of deform-net.')
    p.add_argument('--hyper_hidden_layers', type=int, default=1, help='number of hidden layers hyper-net.')

    opt = p.parse_args()
    main()
```

**Comment by ycjungSubhuman** [comment]
You can write a separate script that loads each saved checkpoint and try to reconstruct 3D shapes in the validation set, check error, and find the best checkpoint with lowest validation error.

**Comment by WangJYao** [comment]
Good weekend!
I have some questions for you.

1. In the second loop of the above code, is the method for calculating the  ”train_loss“  correct? I copied the method in “training_loop_surface.py”.
2. Is the training data set and the verification data set manually divided in the order of sort_info.txt ?
    For example, 1-1268 is the training dataset, and 1269-1282 is the verification dataset.
3. Which function in the project should I use to reconstruct the 3D shapes corresponding to the verification dataset？
4. I found that the model dimension in  “latent_manipulation_caricature.py”  is 1268 + 150. Is it because the facewarehouse dataset is used？
5. If I want to reconstruct a 3D shape from a specified 2DCaricature image, what should I do？

Looking forward to your reply

**Comment by ycjungSubhuman** [comment]
1. if you sum up the losses from model.forward() should be fine.
2. Yes. Split using the order in sort_info.txt. Train -> validation -> test
3. Use the same code as training. This time, freeze the model weights and just optimize latent code.
4. Yes. Additional models from Facewarehouse is used in the training
5. You first need to pick 2D landmark points on them. For example use my landmark annotator (https://github.com/ycjungSubhuman/Landmarker-2D) to annotate 68 landmarks on the caricature image. Tweak run_fitting_2d_68.py to use the new image instead of current one.

**Comment by WangJYao** [comment]
Oh, I still don't know what to do.
Can you take a look at it for me.
For example, how to load the validation dataset.
How to reconstruct  3D shapes.

```
import configargparse
import os
import torch
from torch.utils.data import DataLoader
from dataset_caricshop3d import CaricShop3DTrain
from surface_net import SurfaceDeformationField


def val():
    val_dataset = CaricShop3DTrain(opt.dir, num_samples=11551)     # Use this method to load the validation dataset ?
    val_dataloader = DataLoader(dataset=val_dataset, batch_size=opt.batch_size)

    checkpoints_dir = os.path.join(opt.model_dir, 'checkpoints')    # model/checkpoints
    # load configs
    meta_params = vars(opt)
    # define DIF-Net
    model = SurfaceDeformationField(1268, **meta_params)
    params = model.parameters()
    optimizer = torch.optim.Adam(params, lr=opt.lr)
    models_list = []    # Save the model to be validated
    for root, dirs, files in os.walk(checkpoints_dir):  
        for filename in files:  
            if filename.endswith('.pth'):  
                model_pth = os.path.join(root, filename)  
                models_list.append(model_pth)  

    for path in models_list:
        model.load_state_dict(torch.load(path))
        
        #  freeze the model weights
        if hasattr(model, 'hyper_net'):
            for param in model.hyper_net.parameters():
                param.requires_grad = False
        if hasattr(model, 'deform_net'):
            for param in model.deform_net.parameters():
                param.requires_grad = False
        model.cuda()
        for epoch in range(opt.epochs):
            for i, (model_input, gt) in enumerate(val_dataloader):
                model_input = {key: value.cuda() for key, value in model_input[0].items()}
                gt = {key: value.cuda() for key, value in gt[0].items()}

                losses = model.forward(model_input, gt)
                val_loss = 0.
                for loss_name, loss in losses.items():
                    single_loss = loss.mean()
                    val_loss += single_loss
                optimizer.zero_grad()
                val_loss.backward()
                optimizer.step()
        # reconstruct  3D shapes



if __name__ == '__main__':
    os.environ['CUDA_VISIBLE_DEVICES'] = '0'

    p = configargparse.ArgumentParser()
    p.add_argument("--dir", type=str, default="dataset", help="3DCaricShop dataset root")
    p.add_argument("--model_dir", type=str, default="model", help="")
    p.add_argument("--epochs", type=int, default=50)
    p.add_argument("--epochs_til_checkpoint", type=int, default=10)
    p.add_argument("--batch_size", type=int, default=4)
    p.add_argument("--lr", type=float, default=1e-4, help="adam: learning rate")
    p.add_argument('--model_type', type=str, default='sine')
    p.add_argument('--latent_dim', type=int, default=128, help='latent code dimension.')
    p.add_argument('--hidden_num', type=int, default=128, help='hidden layer dimension of deform-net.')
    p.add_argument('--num_hidden_layers', type=int, default=3, help='number of hidden layers of deform-net.')
    p.add_argument('--hyper_hidden_layers', type=int, default=1, help='number of hidden layers hyper-net.')

    opt = p.parse_args()
    val()

**Comment by ycjungSubhuman** [comment]
Instead of `params = model.parameters()`, define a tensor of dimension (1, 128) for each mesh to be used for validation. Set requires_grad=True. This will be the latent code to be optimized. Pass that tensor to optim and run the training code, where the only difference is to use model.embedding() instead of model.forward(). Pass the latent code tensor as `embed` of model.embedding() instead of model.forward(). Now the training code will optimize only the latent code, not the model paramters.

For loading validation dataset, you can tweak CaricShop3DTrain a bit to load [1268:(1268+14)] instead of [:1268]. Hope this helps.

**Comment by WangJYao** [comment]
I think I wrote a crazy code. I don't know if it's right.
However, it does generate 14 obj files.
Finally, is "loss.py" used to check errors ?

```
import configargparse
import os
import torch
import utils
import numpy as np
from cyobj.io import read_obj
from torch.utils.data import DataLoader
from dataset_caricshop3d import CaricShop3DVal
from surface_net import SurfaceDeformationField
from surface_deformation import create_mesh, create_mesh_single

def val(V_ref, F):
    val_dataset = CaricShop3DVal(opt.dir, num_samples=11551)  # [num_train:(num_train+num_val)] = [1268:(1268+14)]
    val_dataloader = DataLoader(dataset=val_dataset, batch_size=opt.batch_size)    # batch_size = 1
    checkpoints_dir = os.path.join(opt.model_dir, 'checkpoints2')
    # load configs
    meta_params = vars(opt)
    # define DIF-Net
    model = SurfaceDeformationField(1268, **meta_params)
    models_list = []    # Save the model to be validated
    for root, dirs, files in os.walk(checkpoints_dir):
        for filename in files:
            if filename.endswith('.pth'):
                model_pth = os.path.join(root, filename)
                models_list.append(model_pth)

    for model_path in models_list:
        model.load_state_dict(torch.load(model_path))
        model.cuda()
        save_path = os.path.join(model_path.split('.')[0])      # such as  'model/checkpoints2/model_epoch_0100'
        utils.cond_mkdir(save_path)
        for i, (model_input, gt) in enumerate(val_dataloader):
            model_input = {key: value.cuda() for key, value in model_input[0].items()}
            gt = {key: value.cuda() for key, value in gt[0].items()}

            embedding = torch.zeros(128).float().cuda()
            embedding.requires_grad = True
            optimizer = torch.optim.Adam(lr=opt.lr, params=[embedding])

            for epoch in range(opt.epochs):
                losses = model.embedding(embedding, model_input, gt)
                val_loss = 0.
                for loss_name, loss in losses.items():
                    single_loss = loss.mean()
                    val_loss += single_loss
                optimizer.zero_grad()
                val_loss.backward()
                optimizer.step()
            # reconstruct  3D shapes
            embed_save = embedding.detach().squeeze().cpu().numpy()
            np.savetxt(os.path.join(save_path, 'embedding_epoch_%04d_%d.txt' % (epoch, i)),
                       embed_save)
            create_mesh_single(
                model,
                os.path.join(save_path, 'mesh_{}.obj'.format(i)),
                torch.Tensor(V_ref),
                F,
                embedding=embedding)



if __name__ == '__main__':
    os.environ['CUDA_VISIBLE_DEVICES'] = '0'

    p = configargparse.ArgumentParser()
    p.add_argument("--dir", type=str, default="dataset/3DCaricShop", help="3DCaricShop dataset root")
    p.add_argument("--model_dir", type=str, default="model", help="")
    p.add_argument("--epochs", type=int, default=100)
    p.add_argument("--batch_size", type=int, default=1)
    p.add_argument("--lr", type=float, default=1e-4, help="adam: learning rate")
    p.add_argument('--model_type', type=str, default='sine')
    p.add_argument('--latent_dim', type=int, default=128, help='latent code dimension.')
    p.add_argument('--hidden_num', type=int, default=128, help='hidden layer dimension of deform-net.')
    p.add_argument('--num_hidden_layers', type=int, default=3, help='number of hidden layers of deform-net.')
    p.add_argument('--hyper_hidden_layers', type=int, default=1, help='number of hidden layers hyper-net.')

    opt = p.parse_args()

    path_template = os.path.join('staticdata', 'labelled_tMesh.obj')  # staticdata/labelled_tMesh.obj 
    V_ref, F_ref, _, _, _, _ = read_obj(path_template)
    val(V_ref, F_ref)
```

**Comment by WangJYao** [comment]
Oh, no
I found that the 3D shape it reconstructed was completely different from that in the dataset

**Comment by ycjungSubhuman** [comment]
You can check the error using the loss in loss.py, but please keep in mind to exclude regularization term in the accessment.

**Comment by WangJYao** [comment]
Long time no see.
I use "mse_loss" in "loss. py" to calculate the loss.   Is it correct?
Is the regularization term in the Adam optimizer? How can I exclude it ？
```
            # reconstruct  3D shapes
            embed_save = embedding.detach().squeeze().cpu().numpy()
            np.savetxt(os.path.join(save_path, 'embedding_epoch_%04d_%d.txt' % (epoch, i)),
                       embed_save)                                          # save latent code
            obj_path = os.path.join(save_path, 'mesh_{}.obj'.format(i))     # path to save obj
            create_mesh_single(model, obj_path, torch.Tensor(V_ref), F, embedding=embedding)    # create mesh
            gt_pos, _, _, _, _, _ = read_obj(str(val_objs_path[i]))     # true value of val_obj's vertex position
            new_V, _, _, _, _, _ = read_obj(obj_path)                   # new created vertex position
            gt_pos = torch.from_numpy(gt_pos)
            new_V = torch.from_numpy(new_V)
            obj_loss = torch.nn.functional.mse_loss(new_V, gt_pos)      # calculating losses
```

**Comment by ycjungSubhuman** [comment]
What I mean by the regularization is "embeddings_constraint" in loss.py. If you only used MSE, you are good to go 🙂
________________________________
보낸 사람: WangJYao ***@***.***>
보낸 날짜: 2022년 9월 18일 일요일 오후 2:37
받는 사람: ycjungSubhuman/DeepDeformable3DCaricatures ***@***.***>
참조: 정유철(컴퓨터공학과) ***@***.***>; State change ***@***.***>
제목: Re: [ycjungSubhuman/DeepDeformable3DCaricatures] How to train the model (Issue #2)


Long time no see.
I use "mse_loss" in "loss. py" to calculate the loss. Is it correct?
Is the regularization term in the Adam optimizer? How can I exclude it ？
···
# reconstruct 3D shapes
embed_save = embedding.detach().squeeze().cpu().numpy()
np.savetxt(os.path.join(save_path, 'embedding_epoch_%04d_%d.txt' % (epoch, i)), embed_save)
# save latent code
obj_path = os.path.join(save_path, 'mesh_{}.obj'.format(i)) # path to save obj
create_mesh_single(model, obj_path, torch.Tensor(V_ref), F, embedding=embedding) # create mesh
gt_pos, _, _, _, _, _ = read_obj(str(val_objs_path[i])) # true value of val_obj's vertex position
new_V, _, _, _, _, _ = read_obj(obj_path) # new created vertex position
gt_pos = torch.from_numpy(gt_pos)
new_V = torch.from_numpy(new_V)
obj_loss = torch.nn.functional.mse_loss(new_V, gt_pos) # calculating losses
···
