### ISSUE TITLE
About texture

### ISSUE THREAD

**Issue by cocoaw** [ycjungSubhuman/DeepDeformable3DCaricatures#3]
Hello，thank you for your great work!
but I have some questions about the texture mapping ，your work shows textured 3d models after editing，but I can‘t find related information in your paper, the dataset doesn't have texture information, too. Most work are mapping texture from a fixed image to a 3d model, while aftering editing the 3d model, there is no related accurate image about it, how do you fix it? 
Can you tell me what methods or tools you have used in this step？

**Comment by ycjungSubhuman** [comment]
Hi, We project the input caricature as texture onto the reconstructed 3D mesh. You can refer to the process [here](https://github.com/ycjungSubhuman/DeepDeformable3DCaricatures/blob/79837d04ff9104d889f8bfdeda73c2b0fb896a77/run_fitting_2d_68.py#L135-L151) 

What it does:
1. Align the model onto image using 2D landmarks
2. Softly deform the 3D model along XY plane to fit 2D landmarks. This fixes misalignment around boundaries in the images. The deformed mesh is only used for obtaining texture coordinates in 3.
3. Use orthogonal projection to obtain texture coordinate (i.e., use the X, Y cooridnate of the vertex position as U, V coordinate)
4. Save .obj with texture coordinates for each vertex
After that, you can use the input caricature image as texture map for the mesh. The rendered result will be a textured mesh.

**Comment by cocoaw** [comment]
thank you for your reply！
how about the mesh after editing？for example,its attribute has been changed,  some semantics (i.e. mouth shape,eye shape) doesn't fit the original caricature image anymore.Can I still softly deform this edited model  to the original caricature landmarks to get its texture coordinates?

**Comment by ycjungSubhuman** [comment]
If vertex 1-to-1 correspondence has been lost, you'll have to find a new set of 3D landmarks on the mesh. (I.e. mark manually or do closest point search)

If you already have a good enough pose, then you can simply skip step 2 and proceed to texture projection. The step is a good-to-have, not a necessary one .

**Comment by ycjungSubhuman** [comment]
If your new shape have a completely different shapes to the original one, you can first do texture projection with the one with exact geometry match, then copy the vertex attributes from them to the new one.
