### ISSUE TITLE
How to obtain latent code of new head with trained model

### ISSUE THREAD

**Issue by mynametia** [ycjungSubhuman/DeepDeformable3DCaricatures#6]
Hi, may I ask how do I obtain the latent code of a new head (not in training set) given a trained model? 

On a similar topic, may I ask if the latent code of the template head is already given or must it be generated anew from a trained model?

Thanks for reading, any help is greatly appreciated!

**Comment by ycjungSubhuman** [comment]
Hi, the latent code for a new 3D mesh should be optimized. You can freeze the model parameters and optimize the latent codes, using the same loss as in the training. The code for this is not in this repository, but a similar code is already implemented in 2D landmark fitting. You can tweak this part to achieve what you want.

The latent code for the template model 'staticdata/labelled_tMesh.obj' is not given, but you can think of the 3D shape of latent code 0 as a new template shape. This will depend on what you want to achieve though.
