### ISSUE TITLE
how to use MeshRenderer.render_mesh_tex method

### ISSUE THREAD

**Issue by luna6r** [ycjungSubhuman/DeepDeformable3DCaricatures#9]
hello. 
I'm unfamiliar with trimesh and pyrender.  And there is no demo code for MeshRenderer.render_mesh_tex method in this project. i wonder if you could give a demo of the method, and show how to get the param VT and texture.
![image](https://user-images.githubusercontent.com/118115264/208440932-8b6e03df-b7ce-484d-bf0e-f47cfd9aae02.png)

**Comment by ycjungSubhuman** [comment]
Hi. Thanks for reaching out. I accidentally left out dead code there. We do not use render_mesh_tex to produce any of the figure in the paper. After runinng run_fitting_2d_68.py, the resulting file would be a set of .obj and .mtl file. If you import .obj file on the mesh rendering program such as MeshLab or Blender, the program would load the textures for the mesh too automatically by reading .mtl file and subsequently the texture image file. You can then render the results using the programs.

Although I did not test this function, I believe this code works, so you can give it a try. I'll provide an example below on how to use this function:
```
from cyobj.io import read_obj
from PIL import Image

path_obj = PATH_OBJ_FILE
path_tex = PATH_TEXTURE # the input 2D caricature image

V, F, VT, FT, _, _ = read_obj(path_obj)
image = Image.open(path_tex)

color = rd.render_mesh_tex(V, F, VT, image)
```
